# Generated by Django 4.2.6 on 2023-10-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auctionlisting_winner_alter_auctionlisting_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='other', max_length=255, unique=True),
        ),
    ]
