# Generated by Django 4.2.6 on 2023-10-23 14:19

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auctionlisting_current_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinLengthValidator(Decimal('0.01'))]),
        ),
    ]
