# Generated by Django 4.2.6 on 2023-10-31 02:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=1024, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
