# Generated by Django 4.2.6 on 2023-10-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_auctionlisting_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
