# Generated by Django 4.2.6 on 2023-11-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_bid_auction_listing_alter_bid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
